name: rocket_chat_dart
description: Similar to Rocket.Chat.Go.SDK and implement APIs according to the Rocket Chat document.
version: 0.0.38
author: haoguo <bard.guo@gmail.com>
homepage: https://github.com/haoguo/rocket.chat.dart
environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  ddp: ^0.0.9
  crypto: ^2.0.6
  http: ^0.12.0
  json_annotation: ^2.0.0
  jaguar_query: 
  jaguar_orm:

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  jaguar_orm_gen:
